account/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns(
    '',
    url(r'^register$', views.register, name='register'),
    url(r'^newUserGuide$', views.newUserGuide, name='newUserGuide'),
    url(r'^sendSmsCheckCode', views.sendSmsCheckCode, name='sendSmsCheckCode'),
    url(r'^login$', views.login, name='login'),
    url(r'^loguot$', views.logout, name='logout'),
    url(r'^recovery$', views.recovery, name='recovery'),
    url(r'^makeSessionExist$', views.makeSessionExist, name='makeSessionExist'),
)

qisite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('www.urls', namespace="home")),
    url(r'^www/', include('www.urls', namespace="www")),
    url(r'^survey/', include('survey.urls', namespace="survey")),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^interface/', include('interface.urls', namespace="interface")),
    url(r'^demos/', include('demos.urls', namespace="demos")),
    url(r'^home/', include('home.urls', namespace="home")),
    #url(r'^restful/', include('restful.urls', namespace="restful")),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

www/urls.py
from django.conf.urls import patterns, url
import views
import services

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='home'),
    url(r'^index$', views.index, name='index'),
    url(r'^help$', views.help, name='help'),
    url(r'^message$', views.message, name='message'),
    url(r'^dialog/confirmDialog$', views.confirmDialog, name='view.dialog.confirmDialog'),
    url(r'^dialog/messageDialog$', views.messageDialog, name='view.dialog.messageDialog'),
    url(r'^django/reverse$', services.djangoReverse, name='service.django.reverse'),
)

www/views.py
# -*- coding: utf-8 -*-
# Create your views here.
from django.template import loader, Context, RequestContext
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse


def index(request):
    '''
    首页
    '''
    template = loader.get_template('www/index.html')
    context = RequestContext(request, {'session': request.session})
    return HttpResponse(template.render(context))


def help(request):
    '''
    帮助页面
    '''
    template = loader.get_template('www/help.html')
    context = RequestContext(request, {'session': request.session})
    return HttpResponse(template.render(context))


def confirmDialog(request):
    '''
    确认框的DOM数据
    '''
    template = loader.get_template('www/dialog/confirmDialog.html')
    context = RequestContext(request, {'session': request.session})
    return HttpResponse(template.render(context))


def messageDialog(request):
    '''
    消息框的DOM数据
    '''
    template = loader.get_template('www/dialog/messageDialog.html')
    context = RequestContext(request, {'session': request.session})
    return HttpResponse(template.render(context))


def message(request):
    '''
    出错提示测试
    '''
    template = loader.get_template('www/message.html')
    context = RequestContext(
        request, {'title': '测试标题', 'message': '测试消息', 'returnUrl': '/'})
    return HttpResponse(template.render(context))

www/templates/www/commoncss.html
<!-- Bootstrap -->
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-switch.min.css">
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-select.min.css">
<link rel="stylesheet" href="/static/jquery/jquery-ui.min.css">
<link rel="stylesheet" href="/static/jquery/jquery-ui.theme.min.css">
<link rel="stylesheet" href="/static/jquery/jquery-ui-timepicker-addon.css">
<link rel="stylesheet" href="/static/jquery/qunit.css">
<link rel="stylesheet" href="/static/www/css/common.css">


<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
    <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

www/templates/www/commonjs.html
{# jQuery相关js引用 #}
<script src="/static/jquery/jquery.min.js"></script>
<script src="/static/jquery/jquery.cookie.js"></script>
<script src="/static/jquery/jquery-ui.min.js"></script>
<script src="/static/jquery/jquery-ui-timepicker-addon.js"></script>
{# <script src="/static/jquery/datepicker-zh-CN.js"></script> #}
<script src="/static/jquery/qunit.js"></script>

{# Bootstrap相关js引用 #}
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/bootstrap/js/bootstrap-switch.min.js"></script>
<script src="/static/bootstrap/js/bootstrap-select.min.js"></script>


{# django设置csrf信息到jQuery的ajax请求的html head信息中 #}
<script src="/static/django/ajax-csrf.js"></script>
<script src="/static/django/django-js-utils.js"></script>
{# 自定义公用javascript脚本 #}
<script src="/static/www/js/sprintf.min.js"></script>
<script src="/static/www/js/common.js"></script>

www/templates/www/errorMessage.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# 加载相关的css #}
    {% include "www/commoncss.html" %}
</head>

<body style="background-color: #e9e7ef">

<div class="container" style="padding-top: 80px;">

    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-exclamation-sign"/>
                    {% if title %}
                        {{ title }}
                    {% else %}
                        出错
                    {% endif %}
                </div>
                <div class="panel-body " align="center" style="height: 180px;">
                    <br><br>

                    <div>
                        {{ errorMessage }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4" align="center">
            <a href="{{ returnUrl }}"
               type="button" class="btn btn-warning ">
                <span class="glyphicon glyphicon-repeat"></span>
                返回
            </a>
        </div>
    </div>

</div>


{% include "www/commonjs.html" %}
</body>
</html>

www/templates/www/help.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <title> QI 微调查 </title>
    {% include "www/commoncss.html" %}
</head>

<body>

{% include "www/navbar.html" with position="help" %}
<div class="container" style="padding-top: 30px;">
    <div class="row">
        <div class="col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="300x200"
                     src="/static/www/pic/test.png"
                     style="width: 300px; height: 200px;">

                <div class="row">
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <h5>帮助主题1</h5>
                    </div>
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <a href="#" class="btn btn-default" role="button"> 查 看 &raquo;</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="300x200"
                     src="/static/www/pic/test.png"
                     style="width: 300px; height: 200px;">

                <div class="row">
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <h5>帮助主题2</h5>
                    </div>
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <a href="#" class="btn btn-default" role="button"> 查 看 &raquo;</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="300x200"
                     src="/static/www/pic/test.png"
                     style="width: 300px; height: 200px;">

                <div class="row">
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <h5>帮助主题3</h5>
                    </div>
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <a href="#" class="btn btn-default" role="button"> 查 看 &raquo;</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="300x200"
                     src="/static/www/pic/test.png"
                     style="width: 300px; height: 200px;">

                <div class="row">
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <h5>帮助主题4</h5>
                    </div>
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <a href="#" class="btn btn-default" role="button"> 查 看 &raquo;</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="300x200"
                     src="/static/www/pic/test.png"
                     style="width: 300px; height: 200px;">

                <div class="row">
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <h5>帮助主题5</h5>
                    </div>
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <a href="#" class="btn btn-default" role="button"> 查 看 &raquo;</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="thumbnail">
                <img data-src="holder.js/300x200" alt="300x200"
                     src="/static/www/pic/test.png"
                     style="width: 300px; height: 200px;">

                <div class="row">
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <h5>帮助主题6</h5>
                    </div>
                    <div class="col-md-4 col-md-offset-4" align="center">
                        <a href="#" class="btn btn-default" role="button"> 查 看 &raquo;</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% include "www/commonjs.html" %}

</body>
</html>

www/templates/www/index.html
<!DOCTYPE html>
<html>
<head>
    <title> QI 微调查 </title>
    {% include "www/commoncss.html" %}
</head>

<body>

{% include "www/navbar.html" with position="home" %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>QI 自助信息收集平台</h1>
        <p>在这里，我们可以自助做市场调查、投票、选举、会议回执、会务信息收集、讲师满意度测评……总之，
                只要我们需要一次性收集多人的信息，就可以利用QI平台极大地提升我们的工作效率和效果。
                </p>
        <p><a class="btn btn-primary btn-lg" role="button"> 我来试试 </a></p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <img width="50%" src="/static/www/pic/time.png">
            <h2>节省时间</h2>
            <p>这个世界上最宝贵的是什么？当然时间！如果有个工具它可以替我们节省时间，
                那就等于在延长我们的生命，我们没有理由不紧紧抓住它！就是它了！QI。  </p>
            <p><a class="btn btn-default" href="#" role="button"> 我来试试 &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <img width="50%" src="/static/www/pic/retina.png">
            <h2>极度简单</h2>
            <p>QI是个极简单的“一对多“信息收集工具平台。在任何时候，任何情况下，一旦我们需要收集5人以上的信息，就可以想到让QI来帮助我们了！
                它可以帮助哦们省去整理众多信息的时间，并且会给你简单的分析结果哦！ </p>

            <p><a class="btn btn-default" href="#" role="button"> 我来试试 &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <img width="50%" src="/static/www/pic/share.png">
            <h2>分享更多</h2>
            <p>借助QI，我们可以授权填写人在信息收集过程中查看结果，还可以把最终汇总的漂亮的分析结果方便地通过各种移动互联网渠道分享出去。</p>

            <p><a class="btn btn-default" href="#" role="button">我来试试 &raquo;</a></p>
        </div>
    </div>

    <hr>
    <!--
        <footer>
            <p>&copy; Company 2014</p>
    </footer>
-->

</div>

{% include "www/commonjs.html" %}

</body>
</html>

www/templates/www/message.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# 加载相关的css #}
    {% include "www/commoncss.html" %}
</head>

<body style="background-color: #e9e7ef">

<div class="container" style="padding-top: 80px;">

    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-exclamation-sign"/>
                    {% if title %}
                        {{ title }}
                    {% else %}
                        注意
                    {% endif %}
                </div>
                <div class="panel-body " align="center" style="height: 180px;">
                    <br><br>

                    <div>
                        {{ message }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4" align="center">
            <form action="{{ returnUrl }}" method="post">
                {% csrf_token %}
                {% for name,value in formData.iteritems %}
                    <input name={{ name }} type="hidden" value="{{ value }}"/>
                {% endfor %}
                <button type="submit" class="btn btn-warning ">
                    <span class="glyphicon glyphicon-repeat"></span>
                    返回
                </button>
            </form>
        </div>
    </div>

</div>


{% include "www/commonjs.html" %}
</body>
</html>

www/templates/www/navbar.html
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">

        {# 主菜单 #}
        <ul class="nav navbar-nav">
            <li {% if position == 'home' %} class="active" {% endif %} >
                <a href="{% url 'www:index' %}"> QI微调查</a>
            </li>
            <li {% if position == 'paper' %} class="active" {% endif %} >
                {% if session.user %}<a href="{% url 'survey:view.paper.list' %}">问卷</a>{% endif %}
            </li>
            <li {% if position == 'survey' %} class="active" {% endif %} >
                {% if session.user %}<a href="{% url 'survey:view.survey.list' %}">调查</a>{% endif %}
            </li>
            <li {% if position == 'list' %} class="active" {% endif %} >
                {% if session.user %}<a href="{% url 'survey:view.custList.list' %}">清单</a>{% endif %}
            </li>
            <li {% if position == 'help' %} class="active" {% endif %} >
                <a href="{% url 'www:help' %}">帮助</a>
            </li>
        </ul>

        {% if session.user %}
            {# 显示用户信息和退出按钮 #}
            <div class="navbar-collapse collapse">
                {# 退出按钮 #}
                <form class="navbar-form navbar-right" role="form" action="{% url 'account:logout' %}">

                    <button type="submit" class="btn btn-warning">退出</button>
                </form>

                {# 显示用户信息和设置按钮 #}
                <ul class="nav navbar-nav navbar-right">
                    {#  用户信息 #}
                    <li>
                        <a>
                            <span class="glyphicon glyphicon-user"></span>
                            {{ session.user.name }}
                            ({{ session.user.phone }})
                        </a>
                    </li>
                    {# 设置按钮 #}
                    <li>
                        <a>
                            <span class="glyphicon glyphicon-cog"></span>
                        </a>
                    </li>

                </ul>
            </div>
        {% else %}
            {# inline登录界面 #}
            <div class="navbar-collapse collapse">

                {# 注册按钮 #}
                <form class="navbar-form navbar-right" role="form" action="{% url 'account:register' %}">

                    <button type="submit" class="btn btn-primary">注册</button>
                </form>

                {# 登录表单 #}
                <form class="navbar-form navbar-right" role="form"
                      action="{% url 'account:login' %}" method="post">
                    {% csrf_token %}
                    {# 手机号 #}
                    <div class="form-group">
                        <input type="text" placeholder="手机" class="form-control"
                               name="phone" id="phone">
                    </div>
                    {# 密码 #}
                    <div class="form-group">
                        <input type="password" placeholder="密码" class="form-control"
                               name="password" id="password">
                    </div>
                    {# 登录按钮 #}
                    <button type="submit" class="btn btn-success">登陆</button>
                </form>

            </div>
        {% endif %}
        <!--/.navbar-collapse -->
    </div>
</div>

www/templates/www/pager.html
{# 分页控件 #}
<ul class="pager">
    {# 开头 #}
    {% if pageData.has_previous %}
        <li><a href="{{ baseUrl }}">&laquo;</a></li>
    {% else %}
        <li class='disabled'><a href="">&laquo;</a></li>
    {% endif %}

    {# 下一页 #}
    {% if pageData.has_previous %}
        <li><a href="{{ baseUrl }}{{ pageData.previous_page_number }}">上一页</a>
        </li>
    {% else %}
        <li class='disabled'><a href="">上一页</a></li>
    {% endif %}

    {# 当前页显示 #}
    <input class='page-switcher'
           type='text' size="1"
           style="text-align:center"
           value='{{ pageData.number }}'
           data-binding-action="{{ baseUrl }}">
    / {{ pageData.paginator.num_pages }}

    {# 下一页 #}
    {% if pageData.has_next %}
        <li><a href="{{ baseUrl }}{{ pageData.next_page_number }}">下一页</a></li>
    {% else %}
        <li class='disabled'><a href="#">下一页</a></li>
    {% endif %}
    {# 最后 #}
    {% if pageData.has_next %}
        <li>
            <a href="{{ baseUrl }}{{ pageData.paginator.num_pages }}">&raquo;</a>
        </li>
    {% else %}
        <li class='disabled'><a href="#">&raquo;</a></li>
    {% endif %}
</ul>